### ISSUE TITLE
Setting up Hermes for UE 5.1

### ISSUE THREAD

**Issue by davidtveraas** [jorgenpt/Hermes#8]
I did notice that this Plugin is for UE 4, yet Hermes is cited by the RedTalaria Plugin by zosiu, a Plugin which is based on Hermes, that they have tested it for UE 5.1. Could you please help me get Hermes running on UE 5.1? 

I get this error when trying to upload the Hermes Plugin, as is, to UE 5.1:

Missing Modules
The following modules are missing or built with a different engine version:
HermesServer
HermesContentEndpoint
Engine modules cannot be compiled at runtime. Please build through your IDE.

This seems to indicate Hermes needs to be built in UE 5.1 explicitly. I succeeded in building Hermes Core using the RunUAT.bat file included with UE 5.1, but I get a hiccup when I try the same thing with Hermes Branch Support. 

The build process stops here:

Expecting to find a type to be declared in a module rules named 'HermesServer' in UE5Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null.  This type must derive from the 'ModuleRules' type defined by Unreal Build Tool.

Do you know how I help the build tool find what it is looking for? 

Also, I did try using the Hermes Core Plugin without the Hermes Branch Support (since I don't have that one yet). I'm able to Copy assets, but when I paste, I don't see anything, like I'm pasting null data or something. Is this expected without the Brach Support, or is my build broken? 

Thank you for your help.

**Comment by davidtveraas** [comment]
I tried it on another project with a new Plugins folder and it gave me the option to build. Perhaps there is something conflicting with the first project I tried? I am simply trying it out, so this will suffice. I'll close this issue out.

**Comment by jorgenpt** [comment]
@davidtveraas Glad it worked out! If you continue to have problems or you figure out what caused the underlying issue, please let me know or open another ticket. :)
